### ISSUE TITLE
Update doesn't work on macOS

### ISSUE THREAD

**Issue by tihmstar** [JohnDMcMaster/libxgecu#7]
I'm running macOS 14.5 (23F79) on M2.
`poetry run t48_version` works fine, but update doesn't.

```
(libxgecu-py3.12) tMBP:libxgecu tihmstar$ poetry run t48_version
Scanning for devices...
Found device
Bus 002 Device 001: ID a466:0a53
Read 63 bytes from USB
00000000  00 01 30 00 00 01 07 00  32 30 32 34 2D 30 32 2D  |..0.....2024-02-|
<REDACTED>

model: t48
Dev code: <REDACTED>
Serial: <REDACTED>
FW version: 1.00
Manufacture date: 2024-02-2917:45
res00: 00000000  00 01 30 00                                       |..0.            |
res56: 00000000  26 06 00 00 01 00 00                              |&......         |
(libxgecu-py3.12) tMBP:libxgecu tihmstar$ 
```

```
(libxgecu-py3.12) tMBP:libxgecu tihmstar$ poetry run t48_update ~/Desktop/flasher/XgproV1267_Setup/UpdateT48.dat 
Scanning for devices...
Found device
Bus 002 Device 002: ID a466:0a53
55-init
Resetting...
Scanning for devices...
Found device
Bus 002 Device 002: ID a466:0a53
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/tihmstar/Library/Caches/pypoetry/virtualenvs/libxgecu-f46TisoS-py3.12/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tihmstar/Library/Caches/pypoetry/virtualenvs/libxgecu-f46TisoS-py3.12/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/tihmstar/Library/Caches/pypoetry/virtualenvs/libxgecu-f46TisoS-py3.12/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tihmstar/Library/Caches/pypoetry/virtualenvs/libxgecu-f46TisoS-py3.12/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tihmstar/clones/libxgecu/libxgecu/t48/update.py", line 174, in main
    t.reset(mode=0)
  File "/Users/tihmstar/clones/libxgecu/libxgecu/t48/xgecu/t48.py", line 171, in reset
    t = get()
        ^^^^^
  File "/Users/tihmstar/clones/libxgecu/libxgecu/t48/xgecu/t48.py", line 209, in get
    dev.claimInterface(0)
  File "/Users/tihmstar/Library/Caches/pypoetry/virtualenvs/libxgecu-f46TisoS-py3.12/lib/python3.12/site-packages/usb1/__init__.py", line 1146, in claimInterface
    mayRaiseUSBError(
  File "/Users/tihmstar/Library/Caches/pypoetry/virtualenvs/libxgecu-f46TisoS-py3.12/lib/python3.12/site-packages/usb1/__init__.py", line 127, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/Users/tihmstar/Library/Caches/pypoetry/virtualenvs/libxgecu-f46TisoS-py3.12/lib/python3.12/site-packages/usb1/__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorAccess: LIBUSB_ERROR_ACCESS [-3]
(libxgecu-py3.12) tMBP:libxgecu tihmstar$ 
```

**Comment by JohnDMcMaster** [comment]
Hi there! Thanks for reaching out. I haven't been looking at this project too much recently, but there has been a significant amount of T48 activity on #proghq-t48 on the sipr0n discord. I see your email on Twitter, I'll email you a link if you want to join and ask there.

Other than that I know Pete's update was merged recently that changed a number of things. But I'm also not sure how much testing has been done on MacOS (I'm on Linux). Unclear to me for example if claimInterface has some permission issues that need to be handled better in some way (does it run as root?)

Other: what is your interest in T48? This tool suite is for very low level operations (such as running custom firmware on the T48). Most users are better off using the "minipro" command line utility: https://gitlab.com/DavidGriffith/minipro

Its also worth mentioning there are some bit bang commands in stock T48 firmware which may make this level of customization necessary for most users.

**Comment by JohnDMcMaster** [comment]
fixed by PR: https://github.com/JohnDMcMaster/libxgecu/pull/8
